In [3]:
import numpy as np 
vet1 = np.array([2, 4, 6, 8, 10])
vet2 = np.ones((3, 4))
vet3 = np.full((2, 2), 9)
vet4 = np.arange(5)
print(vet1)
print(vet2)
print(vet3)
print(vet4)

[ 2  4  6  8 10]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[9 9]
 [9 9]]
[0 1 2 3 4]


In [4]:
#cria vetor de 5 elementos com numeros aleatorios
vet5 = np.random.random(5)

#cria matriz identidade 3x3
vet6 = np.eye (3)

#cria vetor vazio de 10 inteiros de 16 bytes
vet7 = np.empty((1, 10), dtype=np.int16)
#mostra os elementos do vetor
print(vet7)


[[1 0 0 0 8 0 0 0 0 0]]


In [5]:
a = np.empty((2, 5), dtype= float)

#verifica quantidade de elementos
a.size
#tipo de elemento
a.dtype
#numero de dimensões
a.ndim
#formato linhas e colunas
a.shape
#converte o tipo de elementos
a.astype(np.int16)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int16)

In [ ]:
v1 = np.zero (5)
v2 = np.ones ((2, 2))
V3 = np.full ((1, 2), 3)

#soma cada linha de v3 a v2
v2 + V3

#operação impossivel! dimensoes incompativeis
v1 + v2