In [2]:
import numpy as np 
vet1 = np.array([2, 4, 6, 8, 10])
vet2 = np.ones((3, 4))
vet3 = np.full((2, 2), 9)
vet4 = np.arange(5)
print(vet1)
print(vet2)
print(vet3)
print(vet4)

[ 2  4  6  8 10]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[9 9]
 [9 9]]
[0 1 2 3 4]


In [3]:
vet5 = np.random.random(5)
vet6 = np.eye (3)
vet7 = np.empty((1, 10), dtype=np.int16)
print(vet7)


[[    0     0     0     0 21968 25912   630     0     0     0]]
